Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-02, with the labels that each got.

#198 chore: add PR size labeler
  .github/workflows/labeler.yml
Labels: size/s

#204 feat: Update dependencies and remove needless table
  .github/workflows/deploy-smart.yaml
  .github/workflows/labeler.yaml
  .github/workflows/smart-mainline-protection.yaml
  THIRD-PARTY
  package.json
  serverless.yaml
  yarn.lock
Labels: chore, dependencies, size/xl

#206 docs: update docs & install scripts
  CHANGELOG.md
  CUSTOMIZE.md
  DEVELOPMENT.md
  INSTALL.md
  README.md
  docker/Dockerfile
  package.json
  postman/FHIR_SMART.postman_collection.json
  postman/FHIR_SMART.postman_environment.json
  postman/Fhir.postman_collection.json
  postman/Fhir_Dev_Env.json
  postman/Fhir_Local_Env.json
  postman/Fhir_Prod_Env.json
  resources/architecture-smart.png
  resources/architecture.png
  scripts/init-auth.py
  scripts/install.sh
  scripts/provision-user.py
  scripts/win_install.ps1
  yarn.lock
Labels: documentation, size/xl

#208 feat: bump routing and interface version to use validators
  package.json
  src/config.ts
  yarn.lock
Labels: size/s

#207 docs: Update docs, Third party file & diagram
  CODE_OF_CONDUCT.md
  CUSTOMIZE.md
  DEVELOPMENT.md
  INSTALL.md
  README.md
  THIRD-PARTY
  resources/architecture.png
Labels: documentation, size/xl

#209 chore: update dependencies
  package.json
  yarn.lock
Labels: dependencies, size/s

#210 chore(release): 1.0.0-smart
  CHANGELOG.md
  package.json
Labels: chore, size/s

#220 docs: add a troubleshooting case for windows
  INSTALL.md
Labels: documentation, size/xs

#217 docs: fix link
  DEVELOPMENT.md
Labels: documentation, size/xs

#222 chore: change log retention and add DDB tables as output
  serverless.yaml
Labels: chore, size/s

#224 test: Add SMART negative tests
  .github/workflows/deploy-smart.yaml
  integration-tests/bulkExport.test.ts
  integration-tests/search.test.ts
  integration-tests/smartAuth.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/m

#225 test: Only merge smart-develop to smart-mainline if custom-integration-tests and inferno-test passes
  .github/workflows/deploy-smart.yaml
Labels: size/xs

#223 chore: update docs and extend log retention
  README.md
  resources/oauth2-fwoa-flow.png
  serverless.yaml
Labels: chore, documentation, size/s
