Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-06, with the labels that each got.

#343 fix: Allow running sls offline with Hapi Validator
  DEVELOPMENT.md
  serverless.yaml
  src/config.ts
Labels: size/s

#345 fix: typo for passing in custom log level
  serverless.yaml
Labels: size/xs

#346 chore: script for add alias to existing index
  scripts/elasticsearch-operations.js
Labels: size/s

#347 feat: remove unneeded scope checks in authorizer
  serverless.yaml
Labels: size/xs

#349 feat: Use alias for all ES operations
  package.json
  scripts/elasticsearch-operations.js
  yarn.lock
Labels: size/s

#353 chore(release): 3.0.0
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s

#354 chore: remove routing package from bundle.externals
  package.json
  serverless.yaml
  yarn.lock
Labels: size/s

#356 chore: update dependencies
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/m

#364 feat!: merge in changes from `mainline`
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/miscellaneous.md
  .github/workflows/cfn-analysis.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/labeler.yml
  CHANGELOG.md
  CUSTOMIZE.md
  DEVELOPMENT.md
  README.md
  THIRD-PARTY
  USING_IMPLEMENTATION_GUIDES.md
  auditLogMover/package.json
  auditLogMover/serverless.yaml
  auditLogMover/yarn.lock
  cloudformation/alarms.yaml
  cloudformation/bulkExport.yaml
  cloudformation/elasticsearch.yaml
  integration-tests/implementationGuides.test.ts
  integration-tests/search.test.ts
  integration-tests/types.ts
  integration-tests/utils.ts
  package.json
  scripts/compile-igs.ts
  scripts/elasticsearch-operations.js
  scripts/install.sh
  scripts/win_install.ps1
  serverless.yaml
  src/config.ts
  src/implementationGuides/IGCompiler.ts
  yarn.lock
Labels: chore, size/xl

#365 feat: update smart dependency
  package.json
  src/authZConfig.ts
  yarn.lock
Labels: dependencies, size/s

#366 chore(release): 2.0.0-smart
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: documentation, size/s

#369 chore: remove unused scripts
  package.json
Labels: size/xs

#370 chore: Add specifications around Kibana
  INSTALL.md
Labels: documentation, size/xs

#367 feat: update lambda state machine to accommodate tenantId
  bulkExport/glueScripts/export-script.py
  bulkExport/state-machine-definition.yaml
Labels: size/s
