Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-03, with the labels that each got.

#221 feat: add HAPI validator lambda fn
  javaHapiValidatorLambda/.gitignore
  javaHapiValidatorLambda/pom.xml
  javaHapiValidatorLambda/serverless.yml
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/Handler.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/Validator.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/ValidatorResponse.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/models/IgFile.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/models/IgIndex.java
  javaHapiValidatorLambda/src/main/resources/implementationGuides/.gitkeep
  javaHapiValidatorLambda/src/main/resources/log4j2.xml
  javaHapiValidatorLambda/src/test/java/software/amazon/fwoa/ValidatorTest.java
Labels: size/l

#229 test: Add tests for RBAC Auth
  integration-tests/bulkExport.test.ts
  integration-tests/rbac-permission.test.ts
  integration-tests/utils.ts
Labels: size/m

#230 test: update cognito usernames
  .github/workflows/deploy.yaml
Labels: size/xs

#231 test: default fhirClient should use practitioner
  integration-tests/utils.ts
Labels: size/xs

#232 chore: dependency update
  package.json
  yarn.lock
Labels: size/s

#235 feat: Compile IG StructureDefinitions
  package.json
  scripts/compile-igs.ts
  src/config.ts
  src/implementationGuides/IGCompiler.test.ts
  src/implementationGuides/IGCompiler.ts
  src/implementationGuides/loadCompiledIGs.ts
Labels: size/m

#236 feat: add useHapiValidator CFN parameter
  javaHapiValidatorLambda/.gitignore
  serverless.yaml
  src/config.ts
Labels: size/s

#237 test: IGs: Validation during create/update and supportedProfile in CapStatement
  integration-tests/implementationGuides.test.ts
  integration-tests/types.ts
Labels: size/m

#240 chore: Update serverless dependencies and use serverless-bundle to optimize package size
  auditLogMover/package.json
  auditLogMover/serverless.yaml
  auditLogMover/tsconfig.json
  auditLogMover/yarn.lock
  package.json
  scripts/win_install.ps1
  serverless.yaml
  tsconfig.json
  yarn.lock
Labels: size/xl

#241 feat: specify paths to IG resources
  javaHapiValidatorLambda/pom.xml
Labels: size/s

#243 fix: http errors from routing dependency
  serverless.yaml
Labels: size/xs

#244 chore: Update serverless dependencies and use serverless-bundle to optimize package size
  auditLogMover/package.json
  auditLogMover/serverless.yaml
  auditLogMover/tsconfig.json
  auditLogMover/yarn.lock
  package.json
  scripts/win_install.ps1
  serverless.yaml
  tsconfig.json
  yarn.lock
Labels: size/xl

#245 chore: update deploy script for working with local packages
  scripts/fhir-works-deploy.sh
Labels: size/s

#246 chore: update deploy script for working with local packages
  scripts/fhir-works-deploy.sh
Labels: size/s

#247 fix: copy IG files to webpack deployment package
  .gitignore
  serverless.yaml
  src/implementationGuides/loadCompiledIGs.ts
Labels: size/s

#252 chore: update log settings
  serverless.yaml
Labels: size/xs

#253 chore: add encryption, https-only, access logging to all buckets
  cloudformation/bulkExport.yaml
  serverless.yaml
Labels: size/s

#257 chore: update gh actions tu build and deploy hapi validator
  .github/workflows/deploy.yaml
Labels: size/s

#259 chore: Merge feat-igs into develop-smart
  .eslintrc.js
  .github/workflows/deploy-smart.yaml
  .github/workflows/deploy.yaml
  .gitignore
  CODE_OF_CONDUCT.md
  CUSTOMIZE.md
  INSTALL.md
  README.md
  THIRD-PARTY
  cloudformation/kms.yaml
  integration-tests/implementationGuides.test.ts
  integration-tests/search.test.ts
  integration-tests/types.ts
  integration-tests/utils.ts
  javaHapiValidatorLambda/.gitignore
  javaHapiValidatorLambda/THIRD-PARTY
  javaHapiValidatorLambda/pom.xml
  javaHapiValidatorLambda/serverless.yml
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/Handler.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/Validator.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/ValidatorResponse.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/models/IgFile.java
  javaHapiValidatorLambda/src/main/java/software/amazon/fwoa/models/IgIndex.java
  javaHapiValidatorLambda/src/main/resources/implementationGuides/.gitkeep
  javaHapiValidatorLambda/src/main/resources/log4j2.xml
  package.json
  scripts/compile-igs.ts
  serverless.yaml
  src/config.ts
  src/implementationGuides/IGCompiler.test.ts
  src/implementationGuides/IGCompiler.ts
  src/implementationGuides/loadCompiledIGs.ts
  yarn.lock
Labels: size/xl

#258 chore: update Okta GitHub URL
  README.md
Labels: documentation, size/xs

#260 chore: Additional igs updates
  .github/workflows/deploy-smart.yaml
  README.md
  THIRD-PARTY
  USING_IMPLEMENTATION_GUIDES.md
  cloudformation/bulkExport.yaml
  serverless.yaml
Labels: size/l

#263 chore: Update routing dependency. Pass in user agent value
  package.json
  serverless.yaml
  yarn.lock
Labels: size/s

#264 chore: fix gh merge workflow to do ff-only
  .github/workflows/deploy.yaml
Labels: size/s

#265 chore: use our own script instead of merge action
  .github/workflows/deploy.yaml
Labels: size/s

#268 ci: use HAPI validator on integ tests
  .github/workflows/deploy-smart.yaml
Labels: size/xs

#269 ci: use HAPI validator on integ tests
  .github/workflows/deploy.yaml
Labels: size/xs

#270 ci: use correct region for tests
  .github/workflows/deploy-smart.yaml
Labels: size/xs

#271 chore: Update routing package dependency. Update custom agent env var…
  package.json
  serverless.yaml
Labels: size/xs

#272 ci: use correct test credentials
  .github/workflows/deploy-smart.yaml
Labels: size/xs

#274 chore: Update routing package dependency. Update custom agent env varriable with correct package version
  package.json
  serverless.yaml
Labels: size/xs

#275 docs: removing team email from feedback
  README.md
Labels: size/xs
