Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-04, with the labels that each got.

#276 docs: removing team email from feedback
  README.md
Labels: size/xs

#277 fix: fix unable to locate compiledImplementationGuides/* glob
  .gitignore
  compiledImplementationGuides/gitkeep
  yarn.lock
Labels: size/s

#280 fix: exit from installation script if serverless deployment fails
  scripts/install.sh
Labels: size/xs

#282 fix: implementation guides & deployment pipeline
  .github/workflows/deploy-smart.yaml
  .gitignore
  compiledImplementationGuides/gitkeep
  package.json
  scripts/install.sh
  yarn.lock
Labels: bug, size/s

#279 docs: Clarify IG documentation
  USING_IMPLEMENTATION_GUIDES.md
Labels: documentation, size/s

#284 test: add date search integ tests
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/m

#286 chore(release): 2.6.0
  CHANGELOG.md
  package.json
Labels: size/xs

#287 docs: Update CUSTOM_USER_AGENT
  serverless.yaml
Labels: size/xs

#288 fix: update persistence dependency; to fix meta bug
  package.json
  yarn.lock
Labels: bug, size/s

#291 feat: enhance numeric and quantity search
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/m

#294 fix: Suppress deprecation warning when writing to Info_Output.yml during installation
  scripts/install.sh
Labels: size/xs

#295 feat: add DLQ for ddbToEs sync failures
  cloudformation/alarms.yaml
  serverless.yaml
Labels: enhancement, size/s

#298 chore: lock down versions of external deployment dependencies
  scripts/install.sh
  scripts/win_install.ps1
  serverless.yaml
Labels: size/s

#300 fix: increment persistence package
  package.json
  yarn.lock
Labels: chore, dependencies, size/s

#296 feat: Add post search and integ tests
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/m

#302 chore: add security scanning
  .github/workflows/codeql-analysis.yml
Labels: size/s

#299 feat(search): support Period type fields for date params
  integration-tests/search.test.ts
  package.json
  yarn.lock
Labels: size/m

#306 test: add search tests for exact token matching
  integration-tests/search.test.ts
Labels: size/s
