Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-12, with the labels that each got.

#520 feat: bump search version to 3.9.2
  auditLogMover/package.json
  auditLogMover/yarn.lock
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/s

#523 chore(deps): bump log4j-core from 2.13.2 to 2.15.0 in /javaHapiValida…
  javaHapiValidatorLambda/pom.xml
Labels: size/xs

#524 feat: bump search version to 3.9.2
  auditLogMover/package.json
  auditLogMover/yarn.lock
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/m

#525 chore(release): 4.1.0
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s

#522 chore: add unit test coverage and enforcement
  .github/workflows/code-coverage.yml
  codecov.yml
  package.json
Labels: size/s

#517 chore: add docs on troubleshooting logs
  .github/workflows/codeql-analysis.yml
  DEVELOPMENT.md
Labels: size/s

#532 chore(deps): bump log4j-core and log4j-api from 2.16.0 to 2.17.0 in javaHapiValidatorLambda
  javaHapiValidatorLambda/pom.xml
Labels: size/xs
