Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-08, with the labels that each got.

#389 feat: Group export scripts
  bulkExport/extractPatientCompartmentSearchParams.js
  bulkExport/glueScripts/export-script.py
  bulkExport/schema/compartmentdefinition-patient.3.0.2.json
  bulkExport/schema/compartmentdefinition-patient.4.0.1.json
  bulkExport/schema/patientCompartmentSearchParams.3.0.2.json
  bulkExport/schema/patientCompartmentSearchParams.4.0.1.json
  bulkExport/uploadGlueScriptsToS3.ts
  cloudformation/bulkExport.yaml
  serverless.yaml
Labels: size/xl

#394 chore: dependency vulnerability
  package.json
  yarn.lock
Labels: size/s

#392 fix: add multi-tenant metadata route
  serverless.yaml
Labels: size/xs

#395 chore: dependency vulner fix
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/s

#397 fix: allow more concurrent export jobs for multi-tenant deployments
  cloudformation/bulkExport.yaml
  serverless.yaml
Labels: size/xs

#396 fix: change output file type
  .gitignore
  INSTALL.md
  README.md
  scripts/install.sh
  scripts/win_install.ps1
Labels: size/s

#393 test: Group export
  bulkExport/glueScripts/export-script.py
  integration-tests/bulkExport.test.ts
  integration-tests/bulkExportTestHelper.ts
  integration-tests/createGroupMembersBundle.json
Labels: size/m

#398 feat: Es hard delete
  serverless.yaml
Labels: size/xs

#399 docs: update postman collection and docs to use Id token
  .github/workflows/deploy.yaml
  README.md
  postman/Fhir.postman_collection.json
  postman/Fhir_Dev_Env.json
  postman/Fhir_Local_Env.json
  postman/Fhir_Prod_Env.json
  scripts/init-auth.py
  scripts/install.sh
  scripts/provision-user.py
  scripts/win_install.ps1
Labels: size/l

#400 docs: add multi-tenancy docs
  README.md
  USING_MULTI_TENANCY.md
Labels: size/s

#402 chore: add boundary to serverless auto generated role
  serverless.yaml
Labels: size/s

#403 chore: dependency fix
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/s

#409 docs: note difference between solutions and github install
  README.md
Labels: size/xs

#411 feat: update dependencies
  package.json
  yarn.lock
Labels: dependencies, size/s

#410 feat: update all dependencies and update integ tests
  .github/workflows/deploy-smart.yaml
  .gitignore
  INSTALL.md
  README.md
  integration-tests/implementationGuides.test.ts
  package.json
  scripts/compile-igs.ts
  scripts/install.sh
  scripts/win_install.ps1
  serverless.yaml
  yarn.lock
Labels: dependencies, size/m

#412 chore: fix integ test
  integration-tests/rbac-permission.test.ts
Labels: size/xs

#413 chore: fix integ tests
  integration-tests/smartAuth.test.ts
Labels: size/xs

#414 chore(release): 2.1.0-smart
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#415 chore(release): 3.1.0
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#419 chore(release): 4.0.0
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s

#417 test: integ test for binary operations
  integration-tests/binary.test.ts
Labels: size/s

#420 chore: restrict Kibana user creation to be admin only
  cloudformation/elasticsearch.yaml
Labels: chore, size/xs

#421 feat: implement multi-tenancy and group export
  .github/workflows/deploy-smart.yaml
  README.md
  USING_MULTI_TENANCY.md
  bulkExport/extractPatientCompartmentSearchParams.js
  bulkExport/glueScripts/export-script.py
  bulkExport/schema/compartmentdefinition-patient.3.0.2.json
  bulkExport/schema/compartmentdefinition-patient.4.0.1.json
  bulkExport/schema/patientCompartmentSearchParams.3.0.2.json
  bulkExport/schema/patientCompartmentSearchParams.4.0.1.json
  bulkExport/state-machine-definition.yaml
  bulkExport/uploadGlueScriptsToS3.ts
  cloudformation/bulkExport.yaml
  integration-tests/bulkExport.test.ts
  integration-tests/bulkExportTestHelper.ts
  integration-tests/createGroupMembersBundle.json
  integration-tests/multitenancy.test.ts
  integration-tests/smartAuth.test.ts
  integration-tests/utils.ts
  package.json
  postman/FHIR_SMART.postman_collection.json
  serverless.yaml
  src/authZConfig.ts
  src/config.ts
  yarn.lock
Labels: size/xl

#424 feat: enable id only searching for reference types
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
Labels: enhancement, size/xs
