Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-05, with the labels that each got.

#308 chore: add cfn-nag to all yaml changes
  .github/workflows/cfn-analysis.yml
  .github/workflows/codeql-analysis.yml
  auditLogMover/serverless.yaml
  cloudformation/alarms.yaml
  cloudformation/bulkExport.yaml
  cloudformation/elasticsearch.yaml
  serverless.yaml
Labels: chore, size/m

#321 chore: dependency updates
  auditLogMover/yarn.lock
  yarn.lock
Labels: size/s

#322 chore: upgrade dependencies
  package.json
  yarn.lock
Labels: size/s

#328 chore: bump dependency version
  auditLogMover/package.json
  auditLogMover/yarn.lock
Labels: size/s

#326 feat: update IGCompiler to accept OperationDefinition
  src/implementationGuides/IGCompiler.ts
Labels: size/s

#325 chore: adding GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/miscellaneous.md
Labels: size/s

#310 feat: deployment change for adding logging framework
  package.json
  serverless.yaml
  src/config.ts
  yarn.lock
Labels: size/m

#333 chore: workflow only run if yaml/yml is updated
  .github/workflows/cfn-analysis.yml
Labels: chore, size/xs

#332 feat: add $docref implementation
  USING_IMPLEMENTATION_GUIDES.md
  integration-tests/implementationGuides.test.ts
  integration-tests/search.test.ts
  integration-tests/types.ts
  integration-tests/utils.ts
  package.json
  scripts/compile-igs.ts
  src/implementationGuides/IGCompiler.ts
  yarn.lock
Labels: size/m

#339 chore: Dependency fix
  auditLogMover/package.json
  auditLogMover/yarn.lock
Labels: size/s

#338 chore: release 2.8.0
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s
