Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-09, with the labels that each got.

#428 chore: fix integration tests
  integration-tests/search.test.ts
  integration-tests/utils.ts
  yarn.lock
Labels: size/s

#430 feat: update ES to 7.10 and utilize Graviton instances for EC2 clusters
  cloudformation/elasticsearch.yaml
Labels: size/xs

#434 chore: normalize all the line endings
  .github/PULL_REQUEST_TEMPLATE.md
  .github/no-response.yaml
  .npmrc
  .prettierrc.js
  CHANGELOG.md
  CUSTOMIZE.md
  INSTALL.md
  THIRD-PARTY
  auditLogMover/auditLogMoverHelper.test.ts
  auditLogMover/auditLogMoverHelper.ts
  auditLogMover/handler.test.ts
  auditLogMover/handler.ts
  bulkExport/schema/compartmentdefinition-patient.4.0.1.json
  cloudformation/alarms.yaml
  cloudformation/backup.yaml
  cloudformation/bulkExport.yaml
  cloudformation/cognito.yaml
  cloudformation/kms.yaml
  scripts/sort-key-migration.js
  serverless.yaml
  src/RBACRules.ts
  src/config.ts
  src/index.ts
Labels: size/xl

#435 chore: normalize all the line endings
  .github/PULL_REQUEST_TEMPLATE.md
  .github/no-response.yaml
  .github/workflows/labeler.yaml
  .npmrc
  .prettierrc.js
  CUSTOMIZE.md
  INSTALL.md
  auditLogMover/auditLogMoverHelper.test.ts
  auditLogMover/auditLogMoverHelper.ts
  auditLogMover/handler.test.ts
  auditLogMover/handler.ts
  bulkExport/schema/compartmentdefinition-patient.4.0.1.json
  cloudformation/alarms.yaml
  cloudformation/backup.yaml
  cloudformation/bulkExport.yaml
  cloudformation/kms.yaml
  scripts/sort-key-migration.js
  serverless.yaml
  src/authZConfig.ts
  src/config.ts
  src/index.ts
  yarn.lock
Labels: size/xl

#436 chore: bump axios version
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/s

#437 fix: group export with group created before _since
  bulkExport/glueScripts/export-script.py
  integration-tests/bulkExport.test.ts
  integration-tests/bulkExportTestHelper.ts
Labels: size/s

#438 chore: S3 block public access
  auditLogMover/serverless.yaml
  cloudformation/bulkExport.yaml
  serverless.yaml
Labels: size/s

#441 chore: Add encryption to our Glue Job
  bulkExport/uploadGlueScriptsToS3.ts
  cloudformation/bulkExport.yaml
  integration-tests/bulkExportTestHelper.ts
Labels: size/s

#448 chore: resolve transitive dependency on set-value package
  package.json
  yarn.lock
Labels: size/s

#450 fix: give Glue IAM Role access to KMS keys
  cloudformation/bulkExport.yaml
Labels: bug, size/s

#452 fix: handle when failures happen in bulk export
  bulkExport/state-machine-definition.yaml
Labels: bug, size/s

#455 fix: Patient compartment inclusion in group export
  bulkExport/glueScripts/export-script.py
  integration-tests/bulkExportTestHelper.ts
  integration-tests/createGroupMembersBundle.json
Labels: size/s

#458 chore: update custom user agent string
  serverless.yaml
Labels: size/xs

#460 fix: group export
  bulkExport/glueScripts/export-script.py
  bulkExport/state-machine-definition.yaml
  integration-tests/bulkExport.test.ts
  integration-tests/bulkExportTestHelper.ts
  integration-tests/createGroupMembersBundle.json
Labels: size/m

#463 test: fix integ test
  integration-tests/bulkExportTestHelper.ts
Labels: size/xs

#462 fix: Add SNS encryption for FhirWorksAlarm
  cloudformation/alarms.yaml
  cloudformation/kms.yaml
Labels: size/s

#459 chore: fix transitive dependency on set-value in auditLogMover
  auditLogMover/package.json
  auditLogMover/yarn.lock
Labels: size/s

#465 feat: allow async creation of FhirConfig
  src/authZConfig.ts
  src/config.ts
  src/index.ts
Labels: size/s

#464 feat: allow async creation of FhirConfig
  src/config.ts
  src/index.ts
Labels: size/s
