Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-07, with the labels that each got.

#372 fix: pin IG download
  .github/workflows/deploy.yaml
  scripts/compile-igs.ts
Labels: size/xs

#373 chore: update integ tests to download correct IG
  .github/workflows/deploy.yaml
  integration-tests/implementationGuides.test.ts
Labels: chore, size/xs

#382 feat: add "enableMultiTenancy" CFN parameter
  package.json
  serverless.yaml
  src/authZConfig.ts
  src/config.ts
  yarn.lock
Labels: size/s

#381 feat: add "enableMultiTenancy" CFN parameter
  serverless.yaml
  src/config.ts
Labels: size/s

#387 test: add multi-tenancy integ tests
  integration-tests/bulkExport.test.ts
  integration-tests/multitenancy.test.ts
  integration-tests/rbac-permission.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/m

#384 fix: remove _id, _tenantId from bulk export results
  bulkExport/glueScripts/export-script.py
Labels: size/s
