Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2021-11, with the labels that each got.

#502 fix: fix bouncing results issue
  package.json
  yarn.lock
Labels: size/s

#500 test: integration test for chained parameters
  integration-tests/bulkExport.test.ts
  integration-tests/bulkExportTestHelper.ts
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/m

#506 fix: Fix CloudWatch LogGroup name for auditLogMover (#503)
  auditLogMover/serverless.yaml
  serverless.yaml
Labels: size/s

#507 fix: fix bouncing results issue (#502)
  package.json
  yarn.lock
Labels: size/s

#501 chore: update serverless versions
  .github/workflows/cfn-analysis.yml
  .github/workflows/deploy.yaml
  auditLogMover/package.json
  auditLogMover/serverless.yaml
  auditLogMover/yarn.lock
  cloudformation/elasticsearch.yaml
  docker/Dockerfile
  package.json
  scripts/install.sh
  scripts/s3-dist.sh
  scripts/win_install.ps1
  serverless.yaml
  src/index.ts
  yarn.lock
Labels: dependencies, size/xl

#510 feat: Chained parameter, ES logging, SQS encryption
  cloudformation/elasticsearch.yaml
  integration-tests/bulkExport.test.ts
  integration-tests/bulkExportTestHelper.ts
  integration-tests/search.test.ts
  integration-tests/utils.ts
  package.json
  serverless.yaml
  yarn.lock
Labels: size/m

#508 chore: add git secrets scan
  .gitallowed
  .github/workflows/build-and-validate.yaml
Labels: size/s

#511 chore: update serverless versions
  .github/workflows/cfn-analysis.yml
  .github/workflows/deploy-smart.yaml
  auditLogMover/package.json
  auditLogMover/serverless.yaml
  auditLogMover/yarn.lock
  cloudformation/elasticsearch.yaml
  docker/Dockerfile
  package.json
  scripts/install.sh
  scripts/s3-dist.sh
  scripts/win_install.ps1
  serverless.yaml
  src/index.ts
  yarn.lock
Labels: size/xl

#513 chore: update CODEOWNERS
  CODEOWNERS
Labels: size/xs

#514 fix: glue export security name not unique
  cloudformation/bulkExport.yaml
  serverless.yaml
Labels: size/xs
