Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2022-10, with the labels that each got.

#712 chore: update dependencies
  auditLogMover/package.json
  auditLogMover/yarn.lock
Labels: size/m

#713 chore: update install script to node14
  scripts/install.sh
Labels: size/xs

#724 chore: main - upgrade lambdas nodejs16
  integration-tests/infrastructure/subscriptions-endpoint/template.yaml
  javaHapiValidatorLambda/pom.xml
  lib/cdk-infra-stack.ts
  package.json
  yarn.lock
Labels: size/s

#727 chore: smart - update lambdas to nodejs 16
  javaHapiValidatorLambda/pom.xml
  lib/cdk-infra-stack.ts
  package.json
  yarn.lock
Labels: size/s

#729 chore: smart cdk-nag unit tests on warnings and failures
  .github/workflows/cfn-analysis.yml
  package.json
  src/test/cdk-infra.test.ts
  yarn.lock
Labels: size/m
