Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2022-03, with the labels that each got.

#540 fix: add deletion policy to KMS keys
  cloudformation/kms.yaml
Labels: size/xs

#579 perf: partial failures for restHook Lambda
  cloudformation/subscriptions.yaml
  package.json
  serverless.yaml
  src/subscriptions/restHookLambda/allowListUtil.ts
  src/subscriptions/restHookLambda/restHook.test.ts
  src/subscriptions/restHookLambda/restHook.ts
  tsconfig.json
  yarn.lock
Labels: size/m

#573 feat: add support for FHIR Subscriptions
  .eslintrc.js
  .github/workflows/deploy.yaml
  .gitignore
  README.md
  USING_SUBSCRIPTIONS.md
  bulkExport/glueScripts/export-script.py
  cloudformation/subscriptions.yaml
  integration-tests/SubscriptionsHelper.ts
  integration-tests/bulkExport.test.ts
  integration-tests/infrastructure/allowList-integTests.ts
  integration-tests/infrastructure/subscriptions-endpoint/.gitignore
  integration-tests/infrastructure/subscriptions-endpoint/README.md
  integration-tests/infrastructure/subscriptions-endpoint/src/app.js
  integration-tests/infrastructure/subscriptions-endpoint/src/package.json
  integration-tests/infrastructure/subscriptions-endpoint/template.yaml
  integration-tests/subscriptions.test.ts
  integration-tests/utils.ts
  package.json
  resources/FWoA-subscriptions.svg
  serverless.yaml
  src/config.ts
  src/index.ts
  src/subscriptions/allowList.ts
  src/subscriptions/matcherLambda/index.ts
  src/subscriptions/reaperLambda/index.ts
  src/subscriptions/reaperLambda/subscriptionReaper.test.ts
  src/subscriptions/reaperLambda/subscriptionReaper.ts
  src/subscriptions/restHookLambda/allowListUtil.ts
  src/subscriptions/restHookLambda/index.ts
  src/subscriptions/restHookLambda/restHook.test.ts
  src/subscriptions/restHookLambda/restHook.ts
  src/subscriptions/restHookLambda/restHookMultiTenant.test.ts
  tsconfig.json
  yarn.lock
Labels: size/xl

#590 test: fix subscriptions integ tests
  .github/workflows/deploy.yaml
  integration-tests/infrastructure/allowList-integTests.ts
  package.json
  yarn.lock
Labels: size/s

#592 chore(release): 2.4.0-smart
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s

#599 fix: dependabot alert fix for simple-git
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/m

#601 chore: update smart-auth version
  package.json
  yarn.lock
Labels: size/s
