Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2022-02, with the labels that each got.

#555 fix: remove _subscriptionStatus from export result field
  bulkExport/glueScripts/export-script.py
Labels: size/xs

#554 feat: sns, sqs, dlq for Subscriptions
  cloudformation/subscriptions.yaml
  serverless.yaml
Labels: size/m

#558 feat: Rest hook Lambda
  .eslintrc.js
  cloudformation/subscriptions.yaml
  package.json
  serverless.yaml
  src/config.ts
  src/index.ts
  src/subscriptions/allowListUtil.ts
  src/subscriptions/index.ts
  src/subscriptions/restHook.test.ts
  src/subscriptions/restHook.ts
  src/subscriptions/restHookMultiTenant.test.ts
  src/subscriptions/types.ts
  yarn.lock
Labels: size/l

#557 feat: subscriptionReaper
  serverless.yaml
  src/subscriptions/index.ts
  src/subscriptions/subscriptionReaper.test.ts
  src/subscriptions/subscriptionReaper.ts
Labels: size/m

#568 fix: codecov actions should not run on feature branches
  .github/workflows/code-coverage.yml
Labels: size/s

#559 feat: add subscriptionsMatcher Lambda
  .gitignore
  package.json
  serverless.yaml
  src/subscriptions/matcherLambda/index.ts
  src/subscriptions/reaperLambda/index.ts
  src/subscriptions/reaperLambda/subscriptionReaper.test.ts
  src/subscriptions/reaperLambda/subscriptionReaper.ts
  src/subscriptions/restHookLambda/allowListUtil.ts
  src/subscriptions/restHookLambda/index.ts
  src/subscriptions/restHookLambda/restHook.test.ts
  src/subscriptions/restHookLambda/restHook.ts
  src/subscriptions/restHookLambda/restHookMultiTenant.test.ts
  src/subscriptions/types.ts
  yarn.lock
Labels: size/m

#569 test: add Subscriptions test infrastructure/helper
  integration-tests/SubscriptionsHelper.ts
  integration-tests/infrastructure/subscriptions-endpoint/.gitignore
  integration-tests/infrastructure/subscriptions-endpoint/README.md
  integration-tests/infrastructure/subscriptions-endpoint/src/app.js
  integration-tests/infrastructure/subscriptions-endpoint/src/package.json
  integration-tests/infrastructure/subscriptions-endpoint/template.yaml
  integration-tests/subscriptions.test.ts
Labels: size/m

#567 fix: update unit tests for subscription reaper
  src/subscriptions/reaperLambda/index.ts
  src/subscriptions/reaperLambda/subscriptionReaper.test.ts
  src/subscriptions/reaperLambda/subscriptionReaper.ts
Labels: size/s

#572 test: add subscriptions env vars in gh actions
  .github/workflows/deploy.yaml
  integration-tests/infrastructure/allowList-integTests.ts
Labels: size/s

#574 fix: encrypt logs for new Lambda fns
  cloudformation/subscriptions.yaml
  serverless.yaml
Labels: size/s

#575 test: add Subscription reaper tests
  integration-tests/subscriptions.test.ts
  src/subscriptions/reaperLambda/index.ts
  src/subscriptions/reaperLambda/subscriptionReaper.test.ts
  src/subscriptions/reaperLambda/subscriptionReaper.ts
Labels: size/s

#570 feat: emit end to end latency metric from rest-hook Lambda
  package.json
  src/subscriptions/restHookLambda/restHook.ts
  yarn.lock
Labels: size/s

#577 test: add tests for tenant isolation of subscriptions
  integration-tests/subscriptions.test.ts
  integration-tests/utils.ts
  package.json
  yarn.lock
Labels: size/s

#576 feat: add DLQ for matcher Lambda
  serverless.yaml
Labels: size/s

#578 test: add end to end tests for subscriptions
  integration-tests/bulkExport.test.ts
  integration-tests/subscriptions.test.ts
  integration-tests/utils.ts
Labels: size/m
