Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2022-11, with the labels that each got.

#733 chore: update socket.io-parser version
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/m

#736 chore: bump loader-utils and minimatch
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/s

#737 chore: bump socket.io-parser, loader-utils, minimatch version
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/s

#752 test: add more negative integration tests
  integration-tests/smartAuth.test.ts
Labels: chore, size/m

#753 docs: update README with IdP information
  README.md
Labels: size/s
