Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2022-01, with the labels that each got.

#533 feat: add GSI to Resource DDB Table
  serverless.yaml
Labels: size/s

#536 chore(deps): bump log4j-api and log4j-core from 2.17.0 to 2.17.1
  javaHapiValidatorLambda/pom.xml
Labels: size/xs

#537 chore: rerun mainline protection check on PR edit
  .github/workflows/mainline-protection.yaml
Labels: size/s

#538 chore: rerun mainline protection check on PR edit
  .github/workflows/mainline-protection.yaml
  .github/workflows/smart-mainline-protection.yaml
Labels: size/s

#539 chore: add unit test coverage and enforcement
  .github/workflows/code-coverage.yml
  package.json
Labels: size/s

#543 feat: Add data validation for subscription
  USING_SUBSCRIPTIONS.md
  serverless.yaml
  src/config.ts
  src/subscriptions/allowList.ts
Labels: size/m

#548 chore: Bump nanoid version
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/s
