Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2022-09, with the labels that each got.

#689 feat: add support for up to 100 transactions in bundle
  package.json
  yarn.lock
Labels: size/s

#679 feat: add support for up to 100 entries in transactions
  package.json
  yarn.lock
Labels: size/s

#688 fix: resourceType should match POST url
  package.json
  yarn.lock
Labels: size/s

#690 chore(release): v3.1.0-smart
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s

#692 chore(release): v5.1.0
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s

#694 fix: update authz-smart package
  package.json
  yarn.lock
Labels: size/s

#695 chore(release): v3.1.1-smart
  CHANGELOG.md
  package.json
  serverless.yaml
Labels: size/s

#697 test: add search scope-based tests
  integration-tests/search.test.ts
Labels: size/m

#699 test: fix hardcoded test value
  integration-tests/search.test.ts
Labels: size/xs

#700 docs: Update README
  README.md
Labels: size/xs

#701 docs: update README
  README.md
Labels: size/xs

#704 chore: update got and file-type versions
  package.json
  yarn.lock
Labels: size/m
