Repository awslabs/fhir-works-on-aws-deployment, pull requests merged in 2023-01, with the labels that each got.

#773 Update documentation TLS
  README.md
Labels: size/xs

#779 chore: fix dependency version
  auditLogMover/package.json
  auditLogMover/yarn.lock
Labels: size/s

#778 docs: add recommendation for token expiry
  README.md
Labels: size/s

#765 update template instructions for integration tests
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/xs

#764 fix: update documentation for postman collection and environment
  postman/FHIR_SMART.postman_collection.json
Labels: size/m

#785 Doc: smartonfhirfaq
  README.md
  SMART_ON_FHIR_FAQ.MD
Labels: size/s

#786 Doc search updates
  INSTALL.md
  resources/billableperiod.png
  resources/kibanaurl.png
  resources/opensearchservice.png
Labels: size/m

#787 fix no-response
  .github/no-response.yml
Labels: size/xs

#791 Update json 5 version (smart branch)
  auditLogMover/package.json
  auditLogMover/yarn.lock
  package.json
  yarn.lock
Labels: size/s

#794 docs: add log dive instructions
  DEVELOPMENT.md
Labels: size/s

#793 721: [Bug] enableBackup breaks deploy
  lib/backup.ts
Labels: size/xs

#792 721: [Bug] enableBackup breaks deploy
  lib/backup.ts
Labels: size/xs

#795 add no-response as an action
  .github/workflows/no-response.yml
Labels: size/s

#796 [WIP]Fix: Added Documentation, S3 Versioning, enforce https
  README.md
  lib/bulkExport.ts
  lib/cdk-infra-stack.ts
  lib/elasticsearch.ts
Labels: size/s

#801 chore: bump luxon version
  package.json
  yarn.lock
Labels: size/s

#800 fix: add optional input validation
  README.md
  bin/cdk-infra.ts
  cdk.json
  integration-tests/smartAuth.test.ts
  lib/cdk-infra-stack.ts
  package.json
  src/test/cdk-infra.test.ts
  yarn.lock
Labels: size/m

#802 chore: cfn nag
  .github/workflows/cfn-analysis.yml
  bin/cdk-infra.ts
  cdk-nag-deny-list.yaml
  lib/alarms.ts
  lib/bulkExport.ts
  lib/bulkExportStateMachine.ts
  lib/cdk-infra-stack.ts
  lib/elasticsearch.ts
  lib/kms.ts
  lib/subscriptions.ts
  package.json
  yarn.lock
Labels: size/m

#804 chore(release): 3.1.2-smart
  CHANGELOG.md
  lib/cdk-infra-stack.ts
  package.json
  serverless.yaml
  yarn.lock
Labels: size/s
